parameters:
- name: msbuildPlatform
  displayName: msbuildPlatform
  type: string
  default: x64

steps:
- task: CredScan@2
  displayName: 'Run CredScan'
  inputs:
    toolMajorVersion: V2
    debugMode: false
  continueOnError: true

- task: BinSkim@3
  displayName: 'Run BinSkim'
  inputs:
    arguments: 'analyze $(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\*.dll  --recurse --verbose'
  continueOnError: true

- name: vs2022
  displayName: Visual Studio Version
  type: string
  default: true

- task: DeleteFiles@1
  displayName: 'Delete files from $(Build.BinariesDirectory)\RelWithDebInfo'
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo'
    Contents: |
     **/*.obj
     **/*.pdb
     **/*.dll
#Manually set msBuildCommandline so that we can also set CAExcludePath
- task: securedevelopmentteam.vss-secure-development-tools.build-task-prefast.SDLNativeRules@2
  displayName: 'Run the PREfast SDL Native Rules for MSBuild'
  inputs:
    userProvideBuildInfo: msBuildInfo
    msBuildArchitecture: x64
    ${{ if eq(parameters.vs2022, false)}}:
      msBuildVersion: 16.0
      msBuildCommandline: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "$(Build.BinariesDirectory)\RelWithDebInfo\onnxruntime.sln" /p:platform="${{parameters.msbuildPlatform}}" /p:configuration="RelWithDebInfo" /p:CAExcludePath="$(Build.BinariesDirectory);$(Build.SourcesDirectory)\cmake;C:\program files (x86)" /p:VisualStudioVersion="17.0" /m /p:PreferredToolArchitecture=x64'
    ${{ else }}:
      msBuildVersion: 17.0
      msBuildCommandline: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "$(Build.BinariesDirectory)\RelWithDebInfo\onnxruntime.sln" /p:platform="${{parameters.msbuildPlatform}}" /p:configuration="RelWithDebInfo" /p:CAExcludePath="$(Build.BinariesDirectory);$(Build.SourcesDirectory)\cmake;C:\program files (x86)" /p:VisualStudioVersion="17.0" /m /p:PreferredToolArchitecture=x64'
  continueOnError: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
  displayName: 'Create Security Analysis Report'
  inputs:
    BinSkim: true
    BinSkimBreakOn: WarningAbove
    CredScan: true
    SDLNativeRules: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
  displayName: 'Publish Security Analysis Logs'
  continueOnError: true

- task: TSAUpload@2
  displayName: 'TSA upload'
  #condition: and (succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    GdnPublishTsaOnboard: false
    GdnPublishTsaConfigFile: '$(Build.sourcesDirectory)\.gdn\.gdntsa'
  continueOnError: true
