parameters:
  FolderPath: ''
  DisplayName: ''
  DoEsrp: 'false'

steps:
- ${{ if eq(parameters['DoEsrp'], 'true') }}:
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
    displayName: 'ESRP CodeSigning'
    inputs:
      ConnectedServiceName: 'TestCodeSign'
      AppRegistrationClientId: '3636be3b-6fb9-4fa5-8024-e63c32e9f0e0'

      AppRegistrationTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      AuthAKVName: 'olive-package-publish'
      AuthCertName: 'olivepackagepublish1'
      AuthSignCertName: '3636be3b-6fb9-4fa5-8024-e63c32e9f0e0'

      FolderPath: ${{ parameters.FolderPath }}
      Pattern: '*.nupkg'
      SessionTimeout: 90
      ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2'
      MaxConcurrency: 25
