# calls tools/ci_build/get_docker_image.py

parameters:
- name: Dockerfile
  type: string
- name: Context
  type: string
- name: DockerBuildArgs
  type: string
  default: ""
- name: Repository
  type: string

variables:
  ${{ if ne(parameters.DockerBuildArgs, "") }}:
    DockerBuildArgsArgument: "--docker-build-args \"${{ parameters.DockerBuildArgs }}\""

steps:
- template: with-container-registry-steps.yml
  parameters:
    Steps:
    - script: |
        tools/ci_build/get_docker_image.py \
          --dockerfile "${{ parameters.Dockerfile }}" \
          --context "${{ parameters.Context }}" \
          ${{ variables.DockerBuildArgsArgument }} \
          --container-registry onnxruntimebuildcache \
          --repository "${{ parameters.Repository }}"
      displayName: "Get ${{ parameters.Repository }} image"
    ContainerRegistry: onnxruntimebuildcache
