parameters:
- name: DoEsrp
  type: boolean
  default: true

- name: FolderPath
  type: string
  default: ''

- name: DisplayName
  type: string
  default: ''

- name: Pattern
  type: string
  default: '*.dylib'

steps:
- task: EsrpCodeSigning@3
  displayName: ${{ parameters.DisplayName }}
  condition: and(succeeded(), eq('${{ parameters.DoEsrp }}', true))
  inputs:
    ConnectedServiceName: 'OnnxRuntime CodeSign 20190817'
    FolderPath: ${{ parameters.FolderPath }}
    Pattern: ${{ parameters.Pattern }}
    signConfigType: inlineSignParams
    inlineOperation: |
      [
        {
          "keyCode": "CP-401337-Apple",
          "operationSetCode": "MacAppDeveloperSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            }
          ],
          "toolName": "sign",
          "toolVersion": "1.0"
        }
      ]
