parameters:
- name: AdditionalBuildFlags
  displayName: Additional build flags for build.py
  type: string
  default: ''

# Must be 1 or 0
- name: AllowReleasedOpsetOnly
  displayName: Whether unreleased onnx opsets are allowed
  type: number
  default: 1
  values:
  - 1
  - 0

- name: BuildForAllArchs
  displayName: Build for all CPU ARCHs
  type: boolean

- name: WithCache
  displayName: Build with Cache
  type: boolean
  default: false

# these 2 parameters are used for debugging.
- name: SpecificArtifact
  displayName: Use Specific Artifact (Debugging only)
  type: boolean
  default: false

- name: BuildId
  displayName: Pipeline BuildId, you could find it in the URL
  type: string
  default: '0'

stages:
- stage: MacOS_C_API_Packaging_CPU
  dependsOn: []
  jobs:
    - template: mac-cpu-packing-jobs.yml
      parameters:
        MacosArch: 'x86_64'
        AllowReleasedOpsetOnly: ${{ parameters.AllowReleasedOpsetOnly }}
        AdditionalBuildFlags: ${{ parameters.AdditionalBuildFlags }}
        WithCache: ${{ parameters.WithCache }}

    - ${{ if eq(parameters.BuildForAllArchs, true) }}:
      - template: mac-cpu-packing-jobs.yml
        parameters:
          MacosArch: 'arm64'
          AllowReleasedOpsetOnly: ${{ parameters.AllowReleasedOpsetOnly }}
          AdditionalBuildFlags: ${{ parameters.AdditionalBuildFlags }}
          WithCache: ${{ parameters.WithCache }}
      - template: mac-cpu-packing-jobs.yml
        parameters:
          MacosArch: 'universal2'
          AllowReleasedOpsetOnly: ${{ parameters.AllowReleasedOpsetOnly }}
          AdditionalBuildFlags: ${{ parameters.AdditionalBuildFlags }}
          WithCache: ${{ parameters.WithCache }}

- stage: MacOS_C_API_Package_Publish
  dependsOn: MacOS_C_API_Packaging_CPU
  jobs:
    - job: MacOS_C_API_Package_Publish
      pool:
        vmImage: 'macOS-12'
      steps:
      - checkout: none
      - template: flex-downloadPipelineArtifact.yml
        parameters:
          StepName: 'Download Pipeline onnxruntime-osx-x86_64'
          ArtifactName: 'onnxruntime-osx-x86_64'
          TargetPath: '$(Build.ArtifactStagingDirectory)'
          SpecificArtifact: ${{ parameters.specificArtifact }}
          BuildId: ${{ parameters.BuildId }}
      - bash: |
          find . -type f
        workingDirectory: $(Build.ArtifactStagingDirectory)
        displayName: check unzipped files
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/onnxruntime-osx-x86_64-*.tgz'
          destinationFolder: '$(Build.ArtifactStagingDirectory)/onnxruntime-osx-x86_64'
          cleanDestinationFolder: true
      - bash: |
          find $(Build.ArtifactStagingDirectory)/onnxruntime-osx-x86_64 -type f
          mkdir -p $(Build.ArtifactStagingDirectory)/archive
          cp "$(Build.ArtifactStagingDirectory)/testdata/libcustom_op_library.dylib" $(Build.ArtifactStagingDirectory)/archive/libcustom_op_library.dylib
          cp "$(Build.ArtifactStagingDirectory)/onnxruntime-osx-x86_64/onnxruntime-osx-x86_64-1.16.0/lib/libonnxruntime.dylib" $(Build.ArtifactStagingDirectory)/archive/libonnxruntime.dylib
          zip -r archive.zip archive && rm -rf archive
          find . -name "*.zip"
        workingDirectory: $(Build.ArtifactStagingDirectory)
        displayName: zip dylib files
      - template: mac-esrp-dylib.yml
        parameters:
          FolderPath: '$(Build.ArtifactStagingDirectory)'
          DisplayName: 'ESRP - Sign Mac'
          DoEsrp: true
          Pattern: '*.zip'
      - bash: |
          set -ex
          unzip $(Build.ArtifactStagingDirectory)/archive.zip -d $(Build.ArtifactStagingDirectory)
          yes | cp -f $(Build.ArtifactStagingDirectory)/archive/libcustom_op_library.dylib $(Build.ArtifactStagingDirectory)/testdata/libcustom_op_library.dylib
          yes | cp -f $(Build.ArtifactStagingDirectory)/archive/libonnxruntime.dylib $(Build.ArtifactStagingDirectory)/onnxruntime-osx-x86_64/onnxruntime-osx-x86_64-1.16.0/lib/libonnxruntime.dylib
          rm -rf $(Build.ArtifactStagingDirectory)/archive
          find $(Build.ArtifactStagingDirectory) -name "*.dylib" -exec codesign -dvvv {} \;
          find $(Build.ArtifactStagingDirectory) -name "*.dylib" -exec ls -l {} \;
        displayName: 'Verify code signing'
        workingDirectory: $(Build.ArtifactStagingDirectory)

      - ${{ if eq(parameters.BuildForAllArchs, true) }}:
        - template: flex-downloadPipelineArtifact.yml
          parameters:
            StepName: 'Download Pipeline onnxruntime-osx-arm64'
            ArtifactName: 'onnxruntime-osx-arm64'
            TargetPath: '$(Build.ArtifactStagingDirectory)'
            SpecificArtifact: ${{ parameters.specificArtifact }}
            BuildId: ${{ parameters.BuildId }}
        - template: flex-downloadPipelineArtifact.yml
          parameters:
            StepName: 'Download Pipeline onnxruntime-osx-universal2'
            ArtifactName: 'onnxruntime-osx-universal2'
            TargetPath: '$(Build.ArtifactStagingDirectory)'
            SpecificArtifact: ${{ parameters.specificArtifact }}
            BuildId: ${{ parameters.BuildId }}

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'onnxruntime-osx'
          condition: 'succeededOrFailed()'
      - template: component-governance-component-detection-steps.yml
        parameters:
          condition: 'succeeded'
