parameters:
- name: build_py_parameters
  displayName: >
    Extra parameters to pass to build.py. Don't put newlines in here.
  type: string
  default: ''

- name: torch_version
  displayName: >
    torch_version.
  type: string

- name: opset_version
  displayName: >
    opset_version.
  type: string

- name: cuda_version
  displayName: >
    cuda_version.
  type: string

- name: cmake_cuda_architectures
  displayName: >
    cmake_cuda_architectures
  type: string

- name: docker_file
  displayName: >
    docker_file.
  type: string

- name: agent_pool
  displayName: >
    agent_pool.
  type: string

- name: upload_wheel
  displayName: >
    upload_wheel.
  type: string
  default: ''

- name: debug_build
  displayName: >
    debug_build.
  type: boolean
  default: false

- name: SpecificArtifact
  displayName: Use Specific Artifact
  type: boolean
  default: false

- name: BuildId
  displayName: Specific Artifact's BuildId
  type: string
  default: '0'

stages:
- template: py-packaging-training-cuda-stage-steps.yml
  parameters:
    build_py_parameters: ${{ parameters.build_py_parameters }}
    torch_version: ${{ parameters.torch_version }}
    opset_version: ${{ parameters.opset_version }}
    cuda_version: ${{ parameters.cuda_version }}
    cmake_cuda_architectures: ${{ parameters.cmake_cuda_architectures }}
    docker_file: ${{ parameters.docker_file }}
    upload_wheel: ${{ parameters.upload_wheel }}
    debug_build: ${{ parameters.debug_build }}
    stage_name: 'Linux_py_Training_Cuda_Wheels_python38'
    python_version: '3.8'
    SpecificArtifact: ${{ parameters.SpecificArtifact }}
    BuildId: ${{ parameters.BuildId }}
