parameters:
- name: NpmPackagingMode
  displayName: 'NPM packages publish configuration'
  type: string
  default: 'dev'
- name: BuildConfig
  displayName: 'Build config'
  type: string
  values:
  - 'Release'
  - 'MinSizeRel'
  - 'Debug'
  - 'RelWithDebugInfo'
  default: 'Release'
- name: PoolName
  displayName: 'Pool name'
  type: string
- name: PackageName
  displayName: 'Package name'
  type: string
  default: 'NPM_packages'

stages:
- stage: Build_Android_AAR
  displayName: Build Android AAR