parameters:
  NugetPath: ''
  PlatformsSupported: ''
  VerifyNugetSigning: ''

steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python'
      inputs:
        versionSpec: 3.7
		
    - task: CmdLine@1
      displayName: 'Validate Nuget'
      inputs:
        filename: '$(Build.BinariesDirectory)\packages\python\python.exe'
        arguments: '$(Build.SourcesDirectory)\tools\nuget\validate_nuget.py --nuget_path ${{parameters.NugetPath}} --platforms_supported ${{parameters.PlatformsSupported}} --verify_nuget_signing ${{parameters.VerifyNugetSigning}}'
        workingDirectory: "$(Build.BinariesDirectory)"
      continueOnError: false