parameters:
- name: DoEsrp
  type: boolean
  default: true

- name: FolderPath
  type: string
  default: ''

- name: DisplayName
  type: string
  default: ''

- name: Pattern
  type: string
  default: '*.dll'

steps:
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
  displayName: ${{ parameters.DisplayName }}
  condition: and(succeeded(), eq('${{ parameters.DoEsrp }}', true))
  inputs:
    ConnectedServiceName: 'OnnxrunTimeCodeSign_20240611'
    AppRegistrationClientId: '53d54d02-978d-4305-8572-583cf6711c4f'
    AppRegistrationTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
    AuthAKVName: 'buildkeyvault'
    AuthCertName: '53d54d02-SSL-AutoRotate'
    AuthSignCertName: '53d54d02-978d-4305-8572-583cf6711c4f'
    signConfigType: inlineSignParams
    inlineOperation: |
      [
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]

    FolderPath: ${{ parameters.FolderPath }}
    Pattern: ${{ parameters.Pattern }}
    SessionTimeout: 90
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2'
    MaxConcurrency: 25
- task: PowerShell@2
  displayName: 'Sign validation for dll file'
  inputs:
    targetType: 'inline'
    script: |
      $valid_flag=$true
      $normal_sign_status="Valid"

      $dll_file_names=Get-ChildItem -Path ${{ parameters.FolderPath }} .\*.dll -Name

      foreach($file in $dll_file_names)
      {
          $file_path=Join-Path ${{ parameters.FolderPath }} -ChildPath $file
          $sign=Get-AuthenticodeSignature -FilePath $file_path
          $sign_status=$sign.Status.ToString()
          Write-Host $file
          Write-Host $sign_status
          if ($sign_status -ne $normal_sign_status)
          {
              Write-Host "File named" $file "does not have valid sign."
              Write-Host "Sign status: "$sign.status
              Write-Host "Sign message: "$sign.StatusMessage
              $valid_flag=$false
              break
          }
      }

      if ($valid_flag -eq $false)
      {
          Write-Host "Error: sign validation failed."
          exit 1
      }
      else
      {
          Write-Host "sign validation passed."
          exit 0
      }
