jobs:
- job: Build_CPU_EP
  pool: onnxruntime-win-cpu-2022
  timeoutInMinutes: 120
  steps:
  # Onnx has no 3.9 python package available yet, need to use python 3.8
  # to avoid build onnx package
  # pythonVersion can be updated in Azure pipeline settings
  # https://dev.azure.com/onnxruntime/onnxruntime/_build?definitionId=53
  - task: UsePythonVersion@0
    displayName: Use Python $(pythonVersion)
    inputs:
      versionSpec: $(pythonVersion)

  - task: BatchScript@1
    inputs:
      filename: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat"
      arguments: "x64 -vcvars_ver=14.31"
      modifyEnvironment: true
    displayName: Set VS Envs

  - script: |
      where cl
      set
    displayName: check Envs

  - script: set PATH="%VCToolsInstallDir%\bin\Hostx64\x64";%PATH%
    displayName: Set VS PATH

  # Start switching to jdk 11 after the Android Emulator is started since Android SDK manager requires java 8
  - task: JavaToolInstaller@0
    displayName: Use jdk 8
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: java -version
    displayName: check java

  #- script: |
  #    python3 tools/python/run_android_emulator.py ^
  #     --android-sdk-root %ANDROID_SDK_ROOT% ^
  #     --create-avd --system-image "system-images;android-29;google_apis;x86_64" ^
  #     --start --emulator-extra-args="-partition-size 2047" ^
  #      --emulator-pid-file %Build.BinariesDirectory%/emulator.pid
  #  displayName: Start Android emulator

  # without it, it hangs at 'Linking CXX executable onnxruntime_test_all'
  - script: bash tools/ci_build/github/android/setup_gradle_wrapper.sh %cd%
    displayName: Setup gradle wrapper to use gradle 6.8.3

  # Start switching to jdk 11 after the Android Emulator is started since Android SDK manager requires java 8
  - task: JavaToolInstaller@0
    displayName: Use jdk 11
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      python3 tools/ci_build/build.py ^
        --android ^
        --build_dir build ^
        --android_sdk_path %ANDROID_HOME% ^
        --android_ndk_path %ANDROID_NDK_HOME% ^
        --android_abi=x86_64 ^
        --android_api=30 ^
        --parallel ^
        --cmake_generator=Ninja ^
        --build_java ^
        --skip_tests
    displayName: CPU EP, Build, Test
