jobs:
- job: Build_CPU_EP
  pool: onnxruntime-win-cpu-2022
  timeoutInMinutes: 60
  steps:
  # Onnx has no 3.9 python package available yet, need to use python 3.8
  # to avoid build onnx package
  # pythonVersion can be updated in Azure pipeline settings
  # https://dev.azure.com/onnxruntime/onnxruntime/_build?definitionId=53
  - task: UsePythonVersion@0
    displayName: Use Python $(pythonVersion)
    inputs:
      versionSpec: $(pythonVersion)

  - task: BatchScript@1
    inputs:
      filename: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat"
      arguments: "x64 -vcvars_ver=14.31"
      modifyEnvironment: true
    displayName: Set VS Envs

  - script: set PATH="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64";%PATH%
    displayName: Set VS PATH
    
  - script: |
      where cl
      set
    displayName: check Envs

  # without it, it hangs at 'Linking CXX executable onnxruntime_test_all'
  - script: bash tools/ci_build/github/android/setup_gradle_wrapper.sh %cd%
    displayName: Setup gradle wrapper to use gradle 6.8.3
    
  - script: |
      python3 tools/ci_build/build.py ^
        --android ^
        --build_dir build ^
        --android_sdk_path %ANDROID_HOME% ^
        --android_ndk_path %ANDROID_NDK_HOME% ^
        --android_abi=x86_64 ^
        --android_api=30 ^
        --parallel ^
        --cmake_generator=Ninja ^
        --build_java ^
        --skip_tests
    displayName: CPU EP, Build
