jobs:
- job: Build_CPU_EP
  pool: onnxruntime-win-cpu-2022
  timeoutInMinutes: 120
  steps:
  # Onnx has no 3.9 python package available yet, need to use python 3.8
  # to avoid build onnx package
  # pythonVersion can be updated in Azure pipeline settings
  # https://dev.azure.com/onnxruntime/onnxruntime/_build?definitionId=53
  - task: UsePythonVersion@0
    displayName: Use Python $(pythonVersion)
    inputs:
      versionSpec: $(pythonVersion)

  - task: BatchScript@1
    inputs:
      filename: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat"
      arguments: "x64 -vcvars_ver=14.31"
      modifyEnvironment: true
    displayName: Set VS Envs

  - script: |
      where cl
      set
    displayName: check Envs

  - script: set PATH="%VCToolsInstallDir%\bin\Hostx64\x64";%PATH%
    displayName: Set VS PATH

  - script: 'pip install wget'
    displayName: 'Command Line Script'

  - task: PythonScript@0
    displayName: 'Run a Python script'
    inputs:
      scriptSource: inline
      script: |
       import wget
       import zipfile
       import os
     
       print('Beginning file download with wget module')
     
       url = 'https://github.com/intel/haxm/releases/download/v7.7.1/haxm-windows_v7_7_1.zip'
       os.mkdir("c:\haxm")
       path = "c:\haxm\haxm.zip"
       wget.download(url, path)
       with zipfile.ZipFile(path, 'r') as zip_ref:
            zip_ref.extractall("c:\haxm")

  - task: BatchScript@1
    inputs:
      filename: "c:/haxm/silent_install.bat"
      modifyEnvironment: true
    displayName: install haxm

  - script: sc query intelhaxm
    displayName: 'Command Line Script'
    
  # Start switching to jdk 11 after the Android Emulator is started since Android SDK manager requires java 8
  - task: JavaToolInstaller@0
    displayName: Use jdk 8
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: java -version && echo %Build.BinariesDirectory%
    displayName: 'Command Line Script'
    
  - script: |
      python3 tools/python/run_android_emulator.py ^
        --android-sdk-root %ANDROID_SDK_ROOT% ^
        --create-avd --system-image "system-images;android-29;google_apis;x86_64" ^
        --start --emulator-extra-args="-partition-size 2047" ^
        --emulator-pid-file %Build.BinariesDirectory%/emulator.pid
    displayName: Start Android emulator

  # without it, it hangs at 'Linking CXX executable onnxruntime_test_all'
  - script: bash tools/ci_build/github/android/setup_gradle_wrapper.sh %cd%
    displayName: Setup gradle wrapper to use gradle 6.8.3

  # Start switching to jdk 11 after the Android Emulator is started since Android SDK manager requires java 8
  - task: JavaToolInstaller@0
    displayName: Use jdk 11
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      python3 tools/ci_build/build.py ^
        --android ^
        --build_dir build\Windows ^
        --android_sdk_path %ANDROID_HOME% ^
        --android_ndk_path %ANDROID_NDK_HOME% ^
        --android_abi=x86_64 ^
        --android_api=30 ^
        --parallel ^
        --cmake_generator=Ninja ^
        --build_java
    displayName: CPU EP, Build, Test

  - script: |
      python3 tools/python/run_android_emulator.py ^
        --android-sdk-root ${ANDROID_SDK_ROOT} ^
        --stop ^
        --emulator-pid-file $(Build.BinariesDirectory)/emulator.pid
    displayName: Stop Android emulator
    condition: always()
