parameters:
- name: DoBuildWithDebugInfo
  displayName: Create additional build with debug information?
  type: boolean
  default: false

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 39159767b951fead9cb36a36c40d920638796138

stages:

# checks enabled in all builds

- template: templates/android-binary-size-check-stage.yml
  parameters:
    Name: MinimalBaseline
    BuildConfigFile: "tools/ci_build/github/linux/ort_minimal/build_check_binsize_config/android_minimal_baseline.config"
    BinarySizeThresholdInBytes: 1306224
    DoBuildWithDebugInfo: ${{ parameters.DoBuildWithDebugInfo }}

# checks excluded from PR builds

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: templates/android-binary-size-check-stage.yml
    parameters:
      Name: MinimalWithMobilePackageOps
      BuildConfigFile: "tools/ci_build/github/linux/ort_minimal/build_check_binsize_config/android_minimal_with_mobile_package_ops.config"
      DoBuildWithDebugInfo: ${{ parameters.DoBuildWithDebugInfo }}
