parameters:
- name: BuildAndroidBinaries
  type: boolean
  default: true
- name: BuildPythonPackages
  type: boolean
  default: true

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 28723f3e3330e5de156d2179353d45b04339a528

stages:

# build binaries for Android
- ${{ if parameters.BuildAndroidBinaries }}:
  - stage: BuildAndroidBinaries
    dependsOn: []
    jobs:
    - template: templates/android-java-api-aar.yml
      parameters:
        buildConfig: 'Release'
        buildSettings: '$(Build.SourcesDirectory)/tools/ci_build/github/android/default_full_aar_build_settings.json'
        artifactName: 'onnxruntime-android-full-aar'
        job_name_suffix: 'Full'
        publish_executables: '1'
        pool_name: 'Linux-CPU'

# build Python packages
# Linux GPU only
- ${{ if parameters.BuildPythonPackages }}:
  - template: templates/py-packaging-stage.yml
    parameters:
      enable_linux_gpu: true
      enable_linux_gpu_tests: false
      enable_ubuntu_cpu: false
      enable_linux_cpu: false
      enable_windows_cpu: false
      enable_windows_gpu: false
      enable_mac_cpu: false
      enable_mac_silicon: false
      enable_linux_arm: false
