jobs:
- job: Flake8_Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        pip install flake8
        displayName: 'install flake8'

    - script: |
        flake8 tools/ci_build/build.py
        displayName: 'flake8'
