jobs:
- job: Linux_CI_GPU_TENSORRT_Dev
  pool: onnxruntime-tensorrt-linuxbuild 
  variables:
    ALLOW_RELEASED_ONNX_OPSET_ONLY: '1'
  timeoutInMinutes: 90
  steps:
    
    - template: templates/run-docker-build-steps.yml
      parameters:
        # Latest TensorRT container only supports ubuntu18.04
        RunDockerBuildArgs: '-o ubuntu18.04 -d tensorrt-v7.1 -r $(Build.BinariesDirectory) -p 3.6 -x "--build_wheel"'

    - template: templates/component-governance-component-detection-steps.yml
      parameters :
        condition : 'ci_only'

    - template: templates/clean-agent-build-directory-step.yml
