jobs:
- template: templates/mac-ci.yml
  parameters:
    DoNugetPack: 'false'
    BuildCommand: 'python3 $(Build.SourcesDirectory)/tools/ci_build/build.py --skip_submodule_sync --ios --ios_sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk --osx_arch x86_64 --apple_deploy_target 12.1 --use_xcode --config RelWithDebInfo'
    # Enable unreleased onnx opsets in CI builds
    # This facilitates testing the implementation for the new opsets
    AllowReleasedOpsetOnly: '0'
