jobs:
- job: iOS_CI_on_Mac
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 120
  steps:
    - script: 'python3 $(Build.SourcesDirectory)/tools/ci_build/build.py --build_dir iOS --ios --ios_sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk --osx_arch x86_64 --apple_deploy_target 12.1 --use_xcode --config RelWithDebInfo'
      displayName: build iOS test cases and run them.
