resources:
  pipelines:
  - pipeline: build
    source: 'Nuget-CUDA-Packaging-Pipeline'
    trigger: 
      branches:
        include:
        - main
    branch: main

parameters:
  - name: nightly
    type: boolean
    default: true

variables:
  - name: ArtifactFeed
    ${{ if eq(parameters.nightly, true) }}:
      value: ort-cuda-12-nightly
    ${{ else }}:
      value: onnxruntime-cuda-12

stages:
- template: stages/nuget-cuda-publishing-stage.yml
  parameters:
    artifact_feed: $(ArtifactFeed)

- template: stages/java-cuda-publishing-stage.yml
  parameters:
    artifact_feed: $(ArtifactFeed)
