parameters:
  - name: nightly
    type: string
    default: '1'
  - name: runId
    type: string
  - name: project
    type: string
    default: 'Lotus'
  - name: pipeline
    type: string
    default: 'Nuget-CUDA-Packaging-Pipeline'

stages:
- template: stages/nuget-cuda-publishing-stage.yml
  parameters:
    runId: $ {{ parameters.runId }}
    project: ${{ parameters.project }}
    pipeline: ${{ parameters.pipeline }}
    ${{ if ne(parameters.nightly, '1') }}:
      artifact_feed: onnxruntime-cuda-12
    ${{ else }}:
      artifact_feed: ort-cuda-12-nightly