resources:
  pipelines:
  - pipeline: build
    source: 'CUDA-Zip-Nuget-Java-Packaging-Pipeline'
    trigger: 
      branches:
        include:
        - main
        - rel-*
    branch: main

parameters:
  - name: isReleaseBuild
    type: boolean
    default: false

variables:
  - name: ArtifactFeed
    ${{ if eq(parameters.isReleaseBuild, false) }}:
      value: ort-cuda-12-nightly
    ${{ else }}:
      value: onnxruntime-cuda-12

stages:
  - template: templates/publish-nuget-steps.yml
    parameters:
      stage_name: 'Publish_NuGet_Package_And_Report'
      include_cpu_ep: true
      download_artifacts_steps:
        - download: build
          displayName: 'Download Pipeline Artifact - Signed NuGet Package'
          artifact: 'drop-signed-nuget-GPU'
        - script: move "$(Pipeline.Workspace)\build\drop-signed-nuget-GPU\*" $(Build.BinariesDirectory)\nuget-artifact\final-package

  - template: stages/nuget-cuda-publishing-stage.yml
    parameters:
      artifact_feed: $(ArtifactFeed)

  - template: stages/java-cuda-publishing-stage.yml
    parameters:
      artifact_feed: $(ArtifactFeed)