trigger: none

jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'AI-Linux-GPU'
    JobName: 'Onnxruntime_Linux_GPU_Training'
    SubmoduleCheckoutMode: 'recursive'
    # TODO remove --skip_onnx_tests when the test failures are fixed
    BuildCommand: >
      tools/ci_build/github/linux/run_dockerbuild.sh
      -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory)
      -x " 
      --config $(buildConfig) 
      --enable_training
      --skip_onnx_tests
      "
    DoNugetPack: 'false'
    ArtifactName: 'drop-linux'
    TimeoutInMinutes: 90
    Strategy: 
      maxParallel: 2
      matrix:
        Debug:
          buildConfig: Debug
        Release:
          buildConfig: Release

