trigger: none

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 39159767b951fead9cb36a36c40d920638796138

stages:
- stage: "Python_Packaging_ROCm57_Release"
  jobs:
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.8'
      RocmVersion: '5.7'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.9'
      RocmVersion: '5.7'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.10'
      RocmVersion: '5.7'

- stage: "Python_Packaging_ROCm57_Debug"
  jobs:
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.8'
      RocmVersion: '5.7'
      BuildConfig: 'Debug'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.9'
      RocmVersion: '5.7'
      BuildConfig: 'Debug'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.10'
      RocmVersion: '5.7'
      BuildConfig: 'Debug'

- stage: "Python_Packaging_ROCm56_Release"
  condition: ne(variables['ORT_DISABLE_PYTHON_PACKAGE_LOCAL_VERSION'], 'true')
  jobs:
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.8'
      RocmVersion: '5.6'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.9'
      RocmVersion: '5.6'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.10'
      RocmVersion: '5.6'
