trigger: none

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 28723f3e3330e5de156d2179353d45b04339a528

stages:
- template: templates/py-packaging-training-cuda-stage.yml
  parameters:
    build_py_parameters: --enable_training --update --build
    torch_version: '1.11.0'
    opset_version: '14'
    cuda_version: '11.3'
    gcc_version: 10
    cmake_cuda_architectures: 37;50;52;60;61;70;75;80;86
    docker_file: Dockerfile.manylinux2014_training_cuda11_3
    agent_pool: Onnxruntime-Linux-GPU
    upload_wheel: 'yes'
