trigger: none

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 28723f3e3330e5de156d2179353d45b04339a528

stages:
- stage: Python_Packaging
  jobs:
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.7'
      RocmVersion: '4.3.1'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.8'
      RocmVersion: '4.3.1'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.9'
      RocmVersion: '4.3.1'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.7'
      RocmVersion: '5.1.1'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.8'
      RocmVersion: '5.1.1'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.9'
      RocmVersion: '5.1.1'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.7'
      RocmVersion: '5.2'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.8'
      RocmVersion: '5.2'
  - template: templates/rocm.yml
    parameters:        
      PythonVersion: '3.9'
      RocmVersion: '5.2'      
   
