parameters:

- name: build_py_parameters
  displayName: 'Specify extra build parameters'
  type: string
  default: 'NONE'

trigger: none

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 1a61614cabfd6b91c6afd6d9e172cc5b838c65fe

stages:
- template: templates/py-packaging-stage.yml
  parameters:
    ${{ if not(eq(parameters.build_py_parameters, 'NONE')) }}:
      build_py_parameters: ${{ parameters.build_py_parameters }}