jobs:
- job: 'Sign_OV_Files'
  workspace:
    clean: all
  timeoutInMinutes: 3000
  pool: 'onnxruntime-gpu-winbuild'
  
  steps:
    # Download a secure file to the agent machine
    - task: DownloadSecureFile@1
      name: onnxruntimeDlls # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
      inputs:
        secureFile: $(secureFile) # The file name or GUID of the secure file
        #retryCount: 5 # Optional

    - script: 'mkdir $(Build.SourcesDirectory)/Artifact && cp $(onnxruntimeDlls.secureFilePath) $(Build.SourcesDirectory)/Artifact'
      displayName: 'Copy dlls to sources directory'

    - script: 'unzip $(secureFile)'
      displayName: 'Unzip dll files'
      workingDirectory: '$(Build.SourcesDirectory)/Artifact'


    # - template: templates/win-esrp-dll.yml
    #   parameters:
    #     DisplayName: 'ESRP - sign NuGet package'
    #     FolderPath: '$(Build.SourcesDirectory)/Artifact'
    #     DoEsrp: 'true'
    #     Pattern: 'onnxruntime*.dll'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/Artifact'
        artifactName: 'Signed Dlls'
        
    - template: templates/clean-agent-build-directory-step.yml
