jobs:
- job: 'Sign_OV_Files'
  workspace:
    clean: all
  timeoutInMinutes: 3000
  pool: 'onnxruntime-gpu-winbuild'
  
  steps:
    # Download a secure file to the agent machine
    - task: DownloadSecureFile@1
      name: onnxruntimeDlls # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
      inputs:
        secureFile: 'dlls.zip' # The file name or GUID of the secure file
        #retryCount: 5 # Optional
    
    - script: 'echo $(onnxruntimeDlls.secureFilePath)'
    
    # - script: 'unzip $(onnxruntimeDlls.secureFilePath)'
    #   displayName: 'unzip zip file'
    #   workingDirectory: '$(Build.ArtifactStagingDirectory)/'
      
    # - script: 'curl -fsSL "https://github.com/intel/onnxruntime/releases/download/v4.0/gpu_binaries_uep_v4.0.zip" -O'
    #   displayName: 'get gpu zip file'
    #   workingDirectory: '$(Build.ArtifactStagingDirectory)/'
    
    # - script: 'unzip gpu_binaries_uep_v4.0.zip'
    #   displayName: 'unzip gpu zip file'
    #   workingDirectory: '$(Build.ArtifactStagingDirectory)/'

    # - template: templates/win-esrp-dll.yml
    #   parameters:
    #     DisplayName: 'ESRP - sign NuGet package'
    #     FolderPath: '$(Build.ArtifactStagingDirectory)/'
    #     DoEsrp: 'true'
    #     Pattern: 'onnxruntime*.dll'
    
    # - task: CodeSign@1
    #   inputs:
    #     Targets: '*.dll'
        
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     artifactName: 'gpu and cpu binaries'
        
    - template: templates/clean-agent-build-directory-step.yml
