jobs:
- job: Windows_Packaging_GPU_x64
  variables:
    buildDirectory: '$(Build.BinariesDirectory)'
    buildConfig: 'RelWithDebInfo'
    buildArch: 'x64'

  steps:
    - template: templates/set-test-data-variables-step.yml

    - template: templates/windows-build-tools-setup-steps.yml
      parameters:
        EnvSetupScript: 'setup_env_cuda.bat'
        buildArch: 'amd64'  # amd64 is needed for vcvars target arch
        setVcvars: true 

    - template: templates/windows-build-and-test-steps.yml
      parameters:
        buildAdditionalParams: ' --use_openmp --use_cuda --cuda_home="C:\local\cuda-9.1.85-windows10-x64-0" --cudnn_home="C:\local\cudnn-9.1-windows10-x64-v7.1\cuda" '
        buildArch: $(buildArch)
        buildConfig: $(buildConfig)

    - template: templates/windows-artifacts-package-and-publish-steps.yml
      parameters:
        buildConfig: $(buildConfig)
        artifactName: 'onnxruntime-win-gpu-$(buildArch)'

    - template: templates/clean-agent-build-directory-step.yml
