parameters:
- name: RunOnnxRuntimeTests
  displayName: Run Tests?
  type: boolean
  default: true

jobs:
- job: 'build'
  pool: 'Win-CPU-2019'
  strategy:
    matrix:
      x64_debug:
        BuildConfig: 'Debug'
        UseOmp: '--use_openmp'
        EnvSetupScript: setup_env.bat
        buildArch: x64
        additionalBuildFlags: --use_dnnl --build_java --build_nodejs
        msbuildPlatform: x64
        isX86: false
      x64_release:
        BuildConfig: 'RelWithDebInfo'
        UseOmp: ''
        EnvSetupScript: setup_env.bat
        buildArch: x64
        additionalBuildFlags: --use_dnnl --build_java --build_nodejs
        msbuildPlatform: x64
        isX86: false
  variables:
    OrtPackageId: 'Microsoft.ML.OnnxRuntime'
    MsbuildArguments: '-maxcpucount'
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true    
    setVcvars: true
    ALLOW_RELEASED_ONNX_OPSET_ONLY: '0'
  timeoutInMinutes: 120
  workspace:
    clean: all
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: $(buildArch)

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
      force32bit: $(isX86)

  - task: JavaToolInstaller@0
    #Our build machine doesn't have java x86
    condition: and(succeeded(), eq(variables['buildArch'], 'x64'))
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: $(buildArch)
      jdkSourceOption: 'PreInstalled'

  - task: BatchScript@1
    displayName: 'setup env'
    inputs:
      filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\$(EnvSetupScript)'
      modifyEnvironment: true
      workingFolder: '$(Build.BinariesDirectory)'

  - script: |
     set ORT_DOXY_SRC=$(Build.SourcesDirectory)
     set ORT_DOXY_OUT=$(Build.BinariesDirectory)\$(BuildConfig)\$(BuildConfig)
     mkdir %ORT_DOXY_SRC% 
     mkdir %ORT_DOXY_OUT%
     "C:\Program Files\doxygen\bin\doxygen.exe" $(Build.SourcesDirectory)\tools\ci_build\github\Doxyfile_csharp.cfg
     
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'API Documentation Check and generate'

  - script: |
     python -m pip install -r '$(Build.SourcesDirectory)\tools\ci_build\github\windows\requirements_eager.txt'
     python -m pip list
    workingDirectory: '$(Build.BinariesDirectory)'
    displayName: 'Install python modules'
  
  - task: BatchScript@1
    displayName: 'setup env 2'
    inputs:
      filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\$(EnvSetupScript)'
      modifyEnvironment: true
      workingFolder: '$(Build.BinariesDirectory)'

  - script: |
     python -c "import torch; import sys; print(sys.path); print(torch.__file__)"
     python -m pip list
    workingDirectory: '$(Build.BinariesDirectory)'
    displayName: 'Check python modules'

  - task: PythonScript@0
    displayName: 'Build Eager mode'
    inputs:
      scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\build.py'
      arguments: '--config $(BuildConfig) --build_dir $(Build.BinariesDirectory) --build_eager_mode --enable_training --enable_pybind --config Release'
      workingDirectory: '$(Build.BinariesDirectory)'

  - task: DeleteFiles@1
    displayName: 'Delete files from $(Build.BinariesDirectory)\RelWithDebInfo'
    condition: and(succeeded(), eq(variables['BuildConfig'], 'RelWithDebInfo'))
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo'
      Contents: |
       **/*.obj
       **/*.pdb
       **/*.dll

  - task: PostAnalysis@2
    displayName: 'Guardian Break'
    condition: and(succeeded(), and(eq(variables['buildArch'], 'x64'), eq(variables['BuildConfig'], 'RelWithDebInfo')))
    inputs:
      GdnBreakGdnToolSDLNativeRulesSeverity: Warning

  - task: PublishTestResults@2
    displayName: 'Publish unit test results'
    inputs:
      testResultsFiles: '**/*.results.xml'
      searchFolder: '$(Build.BinariesDirectory)/$(BuildConfig)'
      testRunTitle: 'Unit Test Run'
    condition: succeededOrFailed()

  - template: templates/component-governance-component-detection-steps.yml
    parameters :
      condition : 'succeeded'