parameters:
- name: RunOnnxRuntimeTests
  displayName: Run Tests?
  type: boolean
  default: true

stages:
- stage: x64_debug
  jobs:
    - template: templates/win-cpu-ci.yml
      parameters:
        BuildConfig: 'Debug'
        UseOmp: '--use_openmp'
        EnvSetupScript: setup_env.bat
        buildArch: x64
        additionalBuildFlags: --use_dnnl --build_java --build_nodejs
        msbuildPlatform: x64
        isX86: false
        job_name_suffix: x64_debug
        RunOnnxRuntimeTests: ${{ parameters.RunOnnxRuntimeTests }}

- stage: x64_release
  jobs:
    - template: templates/win-cpu-ci.yml
      parameters:
        BuildConfig: 'RelWithDebInfo'
        UseOmp: ''
        EnvSetupScript: setup_env.bat
        buildArch: x64
        additionalBuildFlags: --use_dnnl --build_java --build_nodejs
        msbuildPlatform: x64
        isX86: false
        job_name_suffix: x64_release
        RunOnnxRuntimeTests: ${{ parameters.RunOnnxRuntimeTests }}

- stage: x86_release
  jobs:
    - template: templates/win-cpu-ci.yml
      parameters:
        BuildConfig: 'RelWithDebInfo'
        UseOmp: ''
        EnvSetupScript: setup_env_x86.bat
        buildArch: x86
        additionalBuildFlags:
        msbuildPlatform: Win32
        isX86: true
        job_name_suffix: x86_release
        RunOnnxRuntimeTests: ${{ parameters.RunOnnxRuntimeTests }}

- stage: training_x64_debug
  jobs:
    - template: templates/win-cpu-ci.yml
      parameters:
        BuildConfig: 'Debug'
        UseOmp: '--use_openmp'
        EnvSetupScript: setup_env.bat
        buildArch: x64
        additionalBuildFlags: --enable_training --skip_onnx_tests
        msbuildPlatform: x64
        isX86: false
        job_name_suffix: training_x64_debug
        RunOnnxRuntimeTests: ${{ parameters.RunOnnxRuntimeTests }}

- stage: training_x64_release
  jobs:
    - template: templates/win-cpu-ci.yml
      parameters:
        BuildConfig: 'RelWithDebInfo'
        UseOmp: ''
        EnvSetupScript: setup_env.bat
        buildArch: x64
        additionalBuildFlags: --enable_training --skip_onnx_tests
        msbuildPlatform: x64
        isX86: false
        job_name_suffix: training_x64_release
        RunOnnxRuntimeTests: ${{ parameters.RunOnnxRuntimeTests }}