ep:ACL: '/\bacl\b/i'
ep:ArmNN: '/\barmnn\b/i'
ep:CUDA: '/\bcuda\b/i'
ep:DML:
  - '/\bdirectml\b/i'
  - '/\bdml\b/i'
ep:MIGraphX: /\bmigraphx\b/i'
ep:oneDNN: '/\bonednn\b/i'
ep:OpenVINO: '/\bopen\s*vino\b/i'
ep:RockchipNPU: '/\brockchip\b/i'
ep:TensorRT:
  - '/\btensor\s*rt\b/i'
  - '/\btrt\b/i'
ep:tvm: '/\btvm\b/i'
ep:VitisAI: '/\bvitus(?:ai)?\b/i'
platform:jetson: '/\bjetson\b/i'
platform:mobile:
  - '/\bobj-?c\b/i'
  - '/\bnnnapi\b/i'
  - '/\bcore-?ml\b/i'
platform:windows:
  - '/\bwindows\b/i'
  - '/\bwinrt\b/i'
model:transformer:
  - '/\bbert\b/i'
  - '/\bgpt-?2\b/i'
  - '/\bhugging-?face\b/i'
  - '/\blong-?former\b/i'
  - '/\bt5\b/i'
quantization:
  - '/\bquantiz(?:e|ation)\b/i'
