remote_theme: pmarsceill/just-the-docs
color_scheme: onnxruntime
search_enabled: true
# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2
search.button: true
plugins:
  - jekyll-toc
kramdown:
  parse_block_html: true
  toc_levels: "1,2,3"
logo: "/images/ONNX-Runtime-logo.svg"
aux_links:
  "Get started":
    - "/docs/get-started/"
  "Tutorials":
    - "/docs/tutorials/"
  "How to":
    - "/docs/how-to/"
  "Reference":
    - "/docs/reference/"
  "Resources":
    - "/docs/resources/"
  "GitHub":
    - "https://github.com/microsoft/onnxruntime"
ga_tracking: UA-156955408-1    
