[tool.black]
line-length = 120
# extend-exclude needs to be a regular expression
extend-exclude = "cmake"

[tool.isort]
profile = "black"
line_length = 120
extend_skip_glob = ["cmake/*", "orttraining/*"]

[tool.pydocstyle]
convention = "google"
