[tool.black]
line-length = 120
# extend-exclude needs to be a regular expression
extend-exclude = "cmake|onnxruntime/core/flatbuffers/"

[tool.isort]
profile = "black"
line_length = 120
extend_skip_glob = [
    "cmake/*",
    "orttraining/*",
    "onnxruntime/core/flatbuffers/*",
]
target_version = "py37"

[tool.pydocstyle]
convention = "google"
