# test NuGet package on Win, Linux and MacOS
jobs:
  variables:
  - group: ORT_TEST_DATA_SAS
  env: 
    Test_Data_Download_Key: $(ort-internal-test-data-sas)
- template: test_win.yml
  parameters:
    AgentPool : $(AgentPoolWin)
- template: test_linux.yml
  parameters:
    AgentPool : $(AgentPoolLinux)
- template: test_macos.yml
  parameters:
    AgentPool : $(AgentPoolMacOS)

