parameters:
  TargetPath: $(Build.BinariesDirectory)\final-jar
steps:
- task: CmdLine@2
  displayName: Download Java Tools
  inputs:
    script: |
      pushd ${ {parameters.TargetPath }}
      wget --tries=3 https://oss.sonatype.org/service/local/repositories/releases/content/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar -P ./
      wget --tries=3 https://oss.sonatype.org/service/local/repositories/releases/content/com/google/protobuf/protobuf-java/3.21.7/protobuf-java-3.21.7.jar -P ./
      popd