schedules:
- cron: "0 8 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

jobs: 
- template: templates/cpu.yml
  parameters:
    AgentPool : $(AgentPoolWin)
    DoEsrp: 'true'
    DoCompliance: 'true'
