schedules:
- cron: "0 10 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

variables:
  PackageName: 'Microsoft.ML.OnnxRuntime.MKLML'

jobs: 
- template: templates/cpu-mklml.yml
  parameters:
    AgentPool : $(AgentPoolWin)
    DoEsrp: 'true'
