trigger: none

jobs:
- job: Onnxruntime_Linux_GPU_Inference

  timeoutInMinutes: 60

  variables:
  - group: AzureKeyVault # for $(AZURESASKEY)

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - template: templates/set-test-data-variables-step.yml

  - script: >-
      tools/ci_build/vsts/linux/run_dockerbuild.sh
      -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory) -x "
      --azure_sas_key=$(AZURESASKEY) --test_data_url $(TestDataUrl)
      --test_data_checksum $(TestDataChecksum) --build"
    displayName: 'Command Line Script'
    env:
      AZURESASKEY: $(AZURESASKEY)

  - task: PublishTestResults@2
    displayName: 'Publish unit test results'
    inputs:
      testResultsFiles: '**/*.results.xml'
      searchFolder: '$(Build.BinariesDirectory)'
      testRunTitle: 'Unit Test Run'
    condition: succeededOrFailed()

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  - template: templates/clean-agent-build-directory-step.yml

