trigger: none

jobs:
- job: Onnxruntime_Linux_FPGA

  timeoutInMinutes: 60

  variables:
  - group: AzureKeyVault
  - group: AzureKeyVault packaging access tokens

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - template: templates/set-test-data-variables-step.yml

  - script: 'tools/ci_build/vsts/linux/run_dockerbuild.sh -o ubuntu16.04 -d fpga -r $(Build.BinariesDirectory) -x " --azure_sas_key=$(AZURESASKEY) --test_data_url $(TestDataUrl) --test_data_checksum $(TestDataChecksum)"'
    displayName: 'Command Line Script'
    env:
      AZURESASKEY: $(AZURESASKEY)
      AIINFRA_PAT: $(aiinfra-lotus-package-access-token)
      MSAZURE_PAT: $(msazure-official-package-access-token)
      MSCATAPULT_PAT: $(mscatapult-catapult-package-access-token)
      TZ: UTC

  - task: PublishTestResults@2
    displayName: 'Publish unit test results'
    inputs:
      testResultsFiles: '**/*.results.xml'
      searchFolder: '$(Build.BinariesDirectory)'
      testRunTitle: 'Unit Test Run'
    condition: succeededOrFailed()

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  - template: templates/clean-agent-build-directory-step.yml
