parameters:
- name: artifact_feed
  type: string

stages:
- stage: JAR_Publish_GPU
  dependsOn: []
  jobs:
  - job: JAR_Publish_GPU
    workspace:
      clean: all
    pool: 'onnxruntime-Win-CPU-2022'
    variables:
    - name: SYSTEM_ACCESSTOKEN
      value: $(System.AccessToken)
    - name: ADOFeedName
      value: ${{ parameters.artifact_feed }}
    - name: GDN_CODESIGN_TARGETDIRECTORY
      value: '$(Build.BinariesDirectory)/final-package'
    - name: artifactName
      value: onnxruntime-java-gpu

    steps:
    - script: mkdir "$(GDN_CODESIGN_TARGETDIRECTORY)"

    - download: build
      displayName: 'Download Pipeline Artifact - $(artifactName)'
      artifact: '$(artifactName)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/build/$(artifactName)'
        Contents: |
          onnxruntime_gpu*.jar
          onnxruntime_gpu*.pom
        TargetFolder: '$(GDN_CODESIGN_TARGETDIRECTORY)'
        CleanTargetFolder: true

    - task: PowerShell@2
      displayName: 'Get Jar version number and set variable'
      inputs:
        targetType: 'inline'
        script: |
          $file = Get-ChildItem -Path . -Filter "onnxruntime_gpu*.jar"
          $fileName = $file.Name
          if ($fileName -match "onnxruntime_gpu(\d+\.\d+\.\d+)\.jar") {
              $versionNumber = $matches[1]
              Write-Output "Version number: $versionNumber"
          } else {
              Write-Output "No version number found in the filename."
          }
          Write-Host "$versionNumber"
          Write-Host "##vso[task.setvariable variable=ORT_VERSION;]$versionNumber"
        workingDirectory: '$(GDN_CODESIGN_TARGETDIRECTORY)'

    - task: PowerShell@2
      displayName: 'Bundle Jar and POM files into a single jar file'
      inputs:
        targetType: 'inline'
        script: |
          jar cvf bundle.jar `
            onnxruntime_gpu-*.pom `
            onnxruntime_gpu-*.jar
        workingDirectory: '$(GDN_CODESIGN_TARGETDIRECTORY)'

    - task: Gradle@3
      inputs:
        gradleWrapperFile: '$(Build.SourcesDirectory)/java/gradlew.bat'
        workingDirectory: '$(Build.SourcesDirectory)/java'
        tasks: 'publishToADO'
