parameters:
  - name: runId
  - name: project
    type: string
  - name: pipeline
    type: string
  - name: artifact_feed
    type: string
    default: 'onnxruntime-cuda-12'
  - name: dependencies
    type: string
    default: 'none'

stages:
  - stage: NuGet_Publishing_GPU
    ${{ if ne(parameters.dependencies, 'none') }}:
      dependsOn:
    ${{ if eq(parameters.dependencies, 'none') }}:
      dependsOn: [ ]
    jobs:
      - job:
        pool: 'onnxruntime-Ubuntu2004-AMD-CPU'
        steps:
          - checkout: none
          - script: |
                echo "Build ID: ${{ parameters.runId }}"
                echo "Project: ${{ parameters.project }}"
                echo "Pipeline: ${{ parameters.pipeline }}"
                echo "Artifact Feed: ${{ parameters.artifact_feed }}"
            displayName: 'Print Parameters'
          - task: DownloadPipelineArtifact@2
            displayName: Download NuGet Package
            inputs:
              artifact: drop-signed-nuget-GPU
              targetPath: $(Build.BinariesDirectory)/nuget-artifact/final-package
              ${{ if ne(parameters.runId, 'latest') }}:
                buildType: 'specific'
                project: '${{ parameters.project }}'
                pipeline: '${{ parameters.pipeline }}'
                buildVersionToDownload: 'specific'
                buildId: '${{ parameters.runId }}'
          - script: |
              echo $(Build.BinariesDirectory)/nuget-artifact/final-package
            displayName: List Downloaded Package
          - template: ../nuget/templates/get-nuget-package-version-as-variable.yml
            parameters:
              packageFolder: '$(Build.BinariesDirectory)/nuget-artifact/final-package'

          - task: NuGetCommand@2
            displayName: 'NuGet push onnxruntime'
            inputs:
              command: push
              packagesToPush: $(Build.BinariesDirectory)/nuget-artifact/final-package/*.nupkg'
              publishVstsFeed: ${{ parameters.artifact_feed }}



