parameters:
  - name: build_id
    type: string
  - name: project
    type: string
  - name: pipeline
    type: string
  - name: artifact_feed
    type: string
    default: 'onnxruntime-cuda-12'
  - name: depends_on
    type: string
    default: 'none'

stages:
  - stage: Python_Publishing
    ${{ if ne(parameters.depends_on, 'none') }}:
      dependsOn: [ ${{ parameters.depends_on }} ]
    ${{ else }}:
      dependsOn: [ ]
    jobs:
      - job:
        pool: 'onnxruntime-Win-CPU-2022'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'onnxruntime_gpu'
              targetPath: '$(Build.SourcesDirectory)'
              ${{ if eq(parameters.build_id, 'latest') }}:
                buildType: 'specific'
                project: '$(project)'
                pipeline: '$(pipeline)'
                buildVersionToDownload: '$(build_id)'
            displayName: 'Download Build Artifacts - onnxruntime-gpu'
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
          - script: 'pip install twine==3.4.2'
            displayName: 'Install Twine'
          - task: TwineAuthenticate@1
            displayName: 'Twine Authenticate '
            inputs:
              artifactFeed: PublicPackages/$(artifact_feed)
          - script: 'python -m twine upload -r $(artifact_feed) onnxruntime-gpu/*.whl'
            workingDirectory: '$(Build.SourcesDirectory)'
            displayName: 'Uploading wheels to $(artifact_feed)'
            retryCountOnTaskFailure: 3
