# schedules:
# - cron: "0 8 * * *"
#   displayName: Daily Build
#   branches:
#     include:
#     - master
#   always: true

jobs: 
- template: templates/cpu.yml
  parameters:
    AgentPool : 'Win-CPU-2019'
    DoEsrp: 'true'
    DoCompliance: 'true'
    AdditionalBuildFlags: '--use_openmp'
    ArtifactSuffix: '-OpenMP'
    OrtPackageId: 'Microsoft.ML.OnnxRuntime.OpenMP'
