parameters:
  StageSuffix: ''

jobs:
- job: Nodejs_Test_MacOS_${{ parameters.StageSuffix }}
  dependsOn:
  - Nodejs_Packaging
  condition: succeeded()
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool:
    vmImage: 'macOS-latest'

  variables:
  - name: OnnxRuntimeBuildDirectory
    value: '$(Build.BinariesDirectory)'
  steps:
  - template: test.yml
