parameters:
  AgentPool: 'Win-CPU'
  JobSuffix: ''

jobs:
- job: Nodejs_Test_${{ parameters.JobSuffix }}
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool: ${{ parameters.AgentPool }}
  dependsOn:
  - Nodejs_Packaging_CPU
  condition: succeeded()
  variables:
  - name: OnnxRuntimeBuildDirectory
    value: '$(Build.BinariesDirectory)'
  steps:
  - task: DownloadPipelineArtifact@0
    displayName: 'Download NPM packages'
    inputs:
      artifactName: NPM_packages
      targetPath: '$(Build.BinariesDirectory)/nodejs-artifact'

  - powershell: |
     mkdir e2e_test
     cd e2e_test
     npm init -y
     npm install $((ls $(Build.BinariesDirectory)/nodejs-artifact/*.tgz) -join " ")
     npm -p "require('onnxruntime-node')"
    workingDirectory: '$(Build.BinariesDirectory)'

  - template: ../../templates/component-governance-component-detection-steps.yml
    parameters :
      condition : 'always'

  - template: ../../templates/clean-agent-build-directory-step.yml
