parameters:
  - name: DownloadTRT
    type: boolean
    default: false
  - name: CudaVersion
    type: string
    default: '12.2'
    values:
      - 11.8
      - 12.2
  - name: win_trt_folder
    type: string
    default: ''


steps:
  - ${{ if eq(parameters.DownloadCUDA, true) }}:
    - powershell: |
        azcopy.exe cp --recursive https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.CudaVersion }} $(Agent.TempDirectory)
      displayName: 'Download CUDA SDK v${{ parameters.CudaVersion }}'
    - powershell: |
        Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\v${{ parameters.CudaVersion }}\bin;$(Agent.TempDirectory)\v${{ parameters.CudaVersion }}\extras\CUPTI\lib64"
      displayName: 'Append CUDA SDK Directory to PATH'

    - task: CmdLine@2
      inputs:
        script: |
          echo %PATH%
      displayName: 'Print PATH after download CUDA SDK'
  - ${{ if and(eq(parameters.DownloadTRT, true), ne( parameters.win_trt_folder, '')) }}:
    - powershell: |
        azcopy.exe cp --recursive https://lotusscus.blob.core.windows.net/models/local/${{ parameters.win_trt_folder }} $(Agent.TempDirectory)
      displayName: 'Download ${{ parameters.win_trt_folder }}'

    - powershell: |
        Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\${{ parameters.win_trt_folder }}\lib"
      displayName: 'Append ${{ parameters.win_trt_folder }} Directory to PATH'

    - task: CmdLine@2
      inputs:
        script: |
          echo %PATH%
      displayName: 'Print PATH after download TensorRT'