parameters:
  - name: EnvSetupScript
    type: string
  - name: DownloadCUDA
    type: boolean
    default: false
  - name: DownloadTRT
    type: boolean
    default: false
  - name: PrimaryCUDAVersion
    type: string
    default: '12.2'
  - name: SecondaryCUDAVersion
    type: string
    default: '11.8'

variables:
  - template: templates/common-variables.yml
  - name: win_trt_folder
    ${{ if eq(parameters.CudaVersion, '11.8') }}:
      value: ${{ variables.win_trt_folder_cuda11 }}
    ${{ if eq(parameters.CudaVersion, '12.2') }}:
      value: ${{ variables.win_trt_folder_cuda12 }}

steps:
  - ${{ if eq(parameters.DownloadCUDA, 'true') }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.PrimaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Primary CUDA SDK v${{ parameters.PrimaryCUDAVersion }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.SecondaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Secondary CUDA SDK v${{ parameters.SecondaryCUDAVersion }}'
  - ${{ if eq(parameters.DownloadTRT, 'true') }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/${{ variables.win_trt_folder_cuda11 }}" $(Agent.TempDirectory)
        displayName: 'Download ${{ variables.win_trt_folder_cuda11 }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/${{ variables.win_trt_folder_cuda11 }}" $(Agent.TempDirectory)
        displayName: 'Download ${{ variables.win_trt_folder_cuda11 }}'

  - task: BatchScript@1
    displayName: 'setup env'
    inputs:
      filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\${{ parameters.EnvSetupScript }}'
      arguments: ''
      modifyEnvironment: true
      workingFolder: '$(Build.BinariesDirectory)'
