parameters:
  - name: EnvSetupScript
    type: string
  - name: DownloadCUDA
    type: boolean
    default: false
  - name: PrimaryCUDAVersion
    type: string
    default: '12.2'
  - name: SecondaryCUDAVersion
    type: string
    default: '11.8'
  - name: win_trt_folder
    type: string
    default: ''

steps:
  - ${{ if eq(parameters.DownloadCUDA, 'true') }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.PrimaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Primary CUDA SDK v${{ parameters.PrimaryCUDAVersion }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.SecondaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Secondary CUDA SDK v${{ parameters.SecondaryCUDAVersion }}'
  - ${{ if ne(parameters.win_trt_folder, '') }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/${{ parameters.win_trt_folder }}" $(Agent.TempDirectory)
        displayName: 'Download ${{ parameters.win_trt_folder }}'

  - task: BatchScript@1
    displayName: 'setup env'
    inputs:
      filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\${{ parameters.EnvSetupScript }}'
      arguments: ''
      modifyEnvironment: true
      workingFolder: '$(Build.BinariesDirectory)'