parameters:
- name: WithCache
  displayName: Build with Cache
  type: boolean
  default: false

- name: BuildSteps
  type: stepList

- name: Today
  type: string
  default: ""

- name: CacheDir
  type: string
  default: ""

- name: AdditionalKey
  type: string
  default: ""

steps:
  - ${{ if eq(parameters.WithCache, true) }}:
    - task: Cache@2
      inputs:
        ${{if eq(variables['Build.SourceBranchName'], 'merge')}}:
          key: ' "$(TODAY)" | ${{parameters.AdditionalKey}} | merge '
        ${{else}}:
          key: '"$(TODAY)" | onnxruntime | ${{parameters.AdditionalKey}} | $(Build.SourceVersion) '
        path: $(ORT_CACHE_DIR)
        restoreKeys: |
          "$(TODAY)" | onnxruntime | ${{parameters.AdditionalKey}}
      displayName: Cache Task

  - ${{ parameters.BuildSteps }}

  - ${{ if eq(parameters.WithCache, true) }}:
    - powershell: |
        ccache -sv
        ccache -z
      displayName: cache stat
      env:
        CCACHE_DIR: ${{parameters.CacheDir}}
