name: Update Objective-C API Docs

# Run when the Objective-C API changes or every month so that the artifact does not expire
on:
  push:
    branches:
    - main
    - edgchen1/objc_doc_gen_workflow  # TODO remove
    # paths:
    # - objectivec
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: "apidocs-objectivec"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    name: Generate Objective-C API docs
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2

    - name: Install Jazzy
      run: |
        sudo gem install jazzy --version 0.14.3

    - name: Generate Objective-C docs
      run: |
        set -e
        OUTPUT_DIR="./_site/docs/api/objectivec"
        ORT_VERSION_STRING="$(cat ./VERSION_NUMBER) \(commit $(git rev-parse --short HEAD)\)"
        jazzy --config ./objectivec/docs/jazzy_config.yaml \
              --module-version "${ORT_VERSION_STRING}" \
              --clean --output ${OUTPUT_DIR}
      shell: bash

    - name: Upload new site
      uses: actions/upload-artifact@v3
      with:
        name: onnxruntime-objectivec-apidocs
        path: ./_site
        retention-days: 60
