name: Update C/C++ API Docs
on:
  push:
    branches:
      - main
    paths:
      - include/onnxruntime/core/session
  workflow_dispatch:

concurrency:
  group: "apidocs-c"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    name: Generate C/C++ API docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doxygen and dependencies
        run: |
          sudo apt update
          sudo apt-get install libclang-dev
          sudo apt-get install libclang-cpp14
          wget https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz
          tar xvzf doxygen-1.9.6.linux.bin.tar.gz
      - name: Run doxygen
        run: |
          mkdir -p build/doxygen
          cd docs/c_cxx
          ../../doxygen-1.9.6/bin/doxygen
      - name: Log source commit
        run: git rev-parse --short HEAD > build/doxygen/html/source-version.txt
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/doxygen/html
          target-folder: docs/api/c
          clean: true
