name: Update C/C++ API Docs
on:
  push:
    branches:
      - main

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    name: Generate C/C++ API docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doxygen and dependencies
        run: |
          sudo apt update
          sudo apt-get install libclang-dev
          sudo apt-get install libclang-cpp14
          wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz
          tar xvzf doxygen-1.9.5.linux.bin.tar.gz
      - name: Run doxygen
        run: |
          mkdir -p build/doxygen
          cd docs/c_cxx
          ../../doxygen-1.9.5/bin/doxygen
          rm -rf ../../doxygen-1.9.5
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Move API docs into target area
        run: |
          sudo rm -rf _site/docs/api/c
          sudo mv build/doxygen/html _site/docs/api/c
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
