name: Update Python API Docs
on:
  push:
    branches:
      - main
    paths:
      - onnxruntime/python
  workflow_dispatch:

concurrency:
  group: "apidocs-python"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    name: Generate Python API docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo apt-get install graphviz
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd docs/python
          python3 -m pip install -r requirements.txt
          python3 -m pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ ort-nightly
          python3 -m pip list
      - name: Generate Python docs with Sphinx
        run: |
          cd tools/doc
          ./builddoc.sh /usr/bin ../.. ../../build
      - name: Log source commit
        run: git rev-parse --short HEAD > build/docs/inference/html/source-version.txt
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/docs/inference/html
          target-folder: docs/api/python
          clean: true
