name: Update Java API Docs
on:
  push:
    branches:
      - main
    paths:
      - java
  workflow_dispatch:

concurrency:
  group: "apidocs-java"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    name: Generate Java docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: java
          gradle-executable: java/gradlew
          arguments: javadoc
      - name: Log source commit
        run: git rev-parse --short HEAD > java/build/docs/javadoc/source-version.txt
      - name: Move Java docs into site
        run: |
          rm -rf _site/docs/api/java
          mkdir -p _site/docs/api
          mv java/build/docs/javadoc _site/docs/api/java
      - name: Upload new site
        uses: actions/upload-artifact@v3
        with:
          name: onnxruntime-java-apidocs
          path: site
