name: Update C/C++ API Docs
on:
  push:
    branches:
      - main

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Generate C/C++ API docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doxygen and dependencies
        run: |
          sudo apt update
          sudo apt-get install libclang-dev
          sudo apt-get install libclang-cpp14
          wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz
          tar xvzf doxygen-1.9.5.linux.bin.tar.gz
      - name: Run doxygen
        run: |
          mkdir -p build/doxygen
          cd docs/c_cxx
          ../../doxygen-1.9.5/bin/doxygen
      - uses: actions/upload-artifact@v3
        with:
          name: capidocs
          path: build/doxygen/html
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Clean C API directory
        run: |
          rm -rf docs/api/c
          mkdir -p docs/api/c
      - uses: actions/download-artifact@v3
        with:
          name: capidocs
          path: docs/api/c
      - name: Debug
        run: |
          pwd
          find .
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
