name: Update Java API Docs
on:
  push:
    branches:
      - main
    paths:
      - java
  workflow_dispatch:

concurrency:
  group: "apidocs-java"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Generate Java docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: java
          gradle-executable: java/gradlew
          arguments: javadoc
      - name: Log source commit
        run: git rev-parse --short HEAD > java/build/docs/javadoc/source-version.txt
      - name: Download deployed site
        uses: dawidd6/action-download-artifact@v2
        with:
          name: github-pages
          workflow: jekyll-gh-pages.yml
          path: site
      - name: Unpack site
        run: |
          cd site
          tar xvf artifact.tar
      - name: Move Java docs into site
        run: |
          rm -rf site/docs/api/java
          mv java/build/docs/javadoc site/docs/api/java
      - name: Upload new site
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: site

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
