name: Publish C/C++ API Docs
on:
  push:
    branches:
      - automate-c-apidocs
jobs:
  publish:
    name: Publish API docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: docs/c_cxx/Doxyfile
          doxyfile-path: docs/c_cxx/Doxyfile
 