name: Publish C/C++ API Docs
on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish API docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: build/doxygen/html
          doxyfile-path: docs/c_cxx/Doxyfile
 