name: Update Java API Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Generate Java docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: java
          gradle-executable: java/gradlew
          arguments: javadoc
      - name: Set commit ID
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false
      - name: Java API docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-apidocs-${{ steps.vars.outputs.sha_short }}
          path: |
            java/build/docs/javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: java/build/docs/javadoc
          target-folder: docs/api/java
