name: Update Rust API Docs
on:
  push:
    branches:
      - main
    paths:
      - rust
  workflow_dispatch:


jobs:
  publish:
    name: Generate Rust docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install rustc
      - name: Run rust docs generation
        run: |
           cd rust
           RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --no-deps
      - name: Log source commit
        run: git rev-parse --short HEAD > build/rust/html/source-version.txt
      - name: Move Rust docs into site
        run: |
          rm -rf _site/docs/api/rust
          mkdir -p _site/docs/api
          mv rust/html _site/docs/api/rust
      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: onnxruntime-rust-apidocs
          path: _site
          retention-days: 60
