name: Windows_CI
on:
  push:
    branches:
      - main
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AZCOPY_AUTO_LOGIN_TYPE: MSI
  AZCOPY_MSI_CLIENT_ID: 63b63039-6328-442f-954b-5a64d124e5b4

jobs:
  Windows-CUDA-12:
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-github-vs2022-mms"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download cuda
        run: azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v12.2" cuda_sdk


      - name: Delete build folder
        run: |
          if (Test-Path D:\b) { Remove-Item -Recurse -Force D:\b }
          &tools\ci_build\github\windows\install_third_party_deps.ps1 -cpu_arch x64 -install_prefix D:\b\Debug\installed -build_config Debug

      # The build machine doesn't have a GPU. So the value of CMAKE_CUDA_ARCHITECTURES doesn't matter.
      - name: Build code
        run: python tools\ci_build\build.py --windows_sdk_version 10.0.22621.0 --enable_training --build_java --config Debug --build_dir D:\b --skip_submodule_sync --build_csharp --update --build --parallel --cmake_generator "Visual Studio 17 2022" --build_shared_lib --enable_pybind --use_cuda --cuda_home=${{ github.workspace }}\cuda_sdk\v12.2 --enable_cuda_profiling  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=75

  Vcpkg:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: "Run build.py(x64-windows)"
        run: |
          python tools\ci_build\build.py `
            --build_dir "build/x64-windows" `
            --skip_submodule_sync `
            --compile_no_warning_as_error `
            --skip_tests `
            --parallel `
            --use_vcpkg `
            --cmake_extra_defines "CMAKE_TOOLCHAIN_FILE:FILEPATH=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            --cmake_extra_defines "VCPKG_TARGET_TRIPLET=x64-windows" `
            --cmake_extra_defines "VCPKG_INSTALL_OPTIONS=--x-feature=tests"
        shell: pwsh

      - name: "Run build.py(arm64-windows)"
        run: |
          python tools\ci_build\build.py `
            --build_dir "build/arm64-windows" --arm64 `
            --skip_submodule_sync `
            --compile_no_warning_as_error `
            --skip_tests `
            --parallel `
            --use_vcpkg `
            --cmake_extra_defines "CMAKE_TOOLCHAIN_FILE:FILEPATH=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            --cmake_extra_defines "VCPKG_TARGET_TRIPLET=arm64-windows" `
            --cmake_extra_defines "VCPKG_INSTALL_OPTIONS=--x-feature=tests"
        shell: pwsh
